---
#### Ansible task file to configure PostgreSQL for MSF
# Author: @jamcut
# Version: 0.1
# Overview: Tasks to configure PostgreSQL before installing MSF
# Notes: Include this task file in a Ansible playbook.
#        Assumes PostgreSQL is installed
####

# Add PostgreSQL user for MSF
- name: "Add PostgreSQL User"
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_user: name={{ db_user }} password={{ db_pass }} role_attr_flags=NOSUPERUSER,NOCREATEDB,NOCREATEROLE

# Add PostgreSQL DB for MSF
- name: "Add PostgreSQL DB"
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_db: name={{ db_name }} owner={{ db_user }}

# Create database.yml file
- name: "Create database.yml"
  shell: "echo {{ item }} >> ~/database.yml"
  with_items:
    - "production:"
    - "  adapter: postgresql"
    - "  database: {{ db_name }}"
    - "  username: {{ db_user }}"
    - "  password: {{ db_pass }}"
    - "  host: 127.0.0.1"
    - "  port: 5432"
    - "  pool: 75"
    - "  timeout: 5"