---
# Copyright (c) 2016, Jeff McCutchan [jamcut]
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# Ansible playbook to update a Fedora system and common pentest tools
# Author: @jamcut
# Version: 0.1

- name: Update Fedora System
  hosts: localhost
  vars:
    # update below with a path specific to your system
    base_install_dir: "UPDATE"
  tasks:

  # Update all packages with dnf and update db for mlocate
    - name: "Update installed 
    llpackages"
      become: yes
      become_method: sudo
      dnf: name=* state=latest

    - name: "Update db for mlocate"
      become: yes
      become_method: sudo
      shell: "updatedb"

  # Update tools in the /opt/ directory
    - name: "Update King Phisher"
      git: repo=https://github.com/securestate/king-phisher.git dest={{ base_install_dir }}king-phisher update=yes version=dev

    - name: "Install King Phisher requirements"
      become: yes
      become_method: sudo
      pip: requirements={{ base_install_dir }}king-phisher/requirements.txt

    - name: "Update King Phisher Templates"
      git: repo=https://github.com/securestate/king-phisher-templates.git dest={{ base_install_dir }}king-phisher-templates update=yes

    - name: "Update sqlmap"
      git: repo=https://github.com/sqlmapproject/sqlmap.git dest={{ base_install_dir }}sqlmap update=yes

    - name: "Update CrackMapExec"
      git: repo=https://github.com/byt3bl33d3r/CrackMapExec.git dest={{ base_install_dir }}CrackMapExec update=yes force=yes

    - name: "Update Empire"
      git: repo=https://github.com/PowerShellEmpire/Empire.git dest={{ base_install_dir }}Empire update=yes

    - name: "Update Responder"
      git: repo=https://github.com/SpiderLabs/Responder.git dest={{ base_install_dir }}Responder update=yes

    - name: "Update SS Misc"
      git: repo=git@github.com:securestate/misc.git dest={{ base_install_dir }}ss-misc update=yes

  # Update Metasploit
    - name: "Update Metasploit"
      git: repo=https://github.com/rapid7/metasploit-framework.git dest={{ base_install_dir }}metasploit-framework update=yes

    - name: "Update gems for Metasploit"
      shell: bundle install chdir={{ base_install_dir }}metasploit-framework/
